name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create config file
        run: echo "${{ secrets.SMARTYSTREETS_CONFIG }}" > config.csv